### ISSUE TITLE
Unique Naming and Logging/Storage of Submission Scripts

### ISSUE THREAD

**Issue by robertej-phd** [mit-mc-clas12/clas12simulations#12]
The problem is best described with the following example:

I want to submit 5 jobs (Queue = 5) with 100 events each. I run our software, which creates the submission scripts (clas12.condor, runscript.sh) to do this. I submit to HTCondor.

Before any job has processed (job is idle, or running but not complete) I decide I also want to submit 7 jobs (Queue = 7) with 200 events each. I run our software, which creates the submission scripts, and submit the batch. 

Instead of having 5 jobs with 100 events and 7 jobs with 200 events, I will instead end up with 14 jobs with 200 events each. I.e., files are not passed to HTCondor in a permanent fashion, they are "live" on the subMIT node until processing is complete. 

To fix this, we need to do something like uniquely name each submission script file (maybe just with a unix timestamp even) and store the scripts in their own dedicated folder. After simulations are complete these files can be stored long term, or destroyed to save disc space.

**Comment by Sangbaek** [comment]
This seems somewhat related to an issue that I and Patrick had. We submitted DVCS and SIDIS relentlessly, but we had a SIDIS at DVCS directory and vice versa. We thought it took time for condor to pick runscripts, but the case introduced here is also interesting-probably related?

**Comment by robertej-phd** [comment]
Yes, I think that Patrick talked to me about this after the demonstration
on 3/8/19. I think uniquely naming runscripts and storing them (at least
for the duration of the simulation) will resolve all these issues. I don't
know what else it would be really

**Comment by robertej-phd** [comment]
Feature included in PR#23
