### ISSUE TITLE
Module directory for subprocedures

### ISSUE THREAD

**Issue by Sangbaek** [mit-mc-clas12/clas12simulations#17]
If a python script is only called by another main python script, not by bash shell,
we can regard them as "subpackage." We can make a separate directory for them with __init__.py. This is a super minor thing that can be done afterward.

**Comment by robertej-phd** [comment]
I believe this is now implemented correctly on robertej/clas12simulation fork, and will be included on the next PR. Please close this issue at that time if it is done correctly, otherwise lets talk about this more after the PR
