### ISSUE TITLE
implement Bobby's table design

### ISSUE THREAD

**Issue by maureeungaro** [mit-mc-clas12/clas12simulations#18]

**Comment by Sangbaek** [comment]
https://dbdiagram.io/d/5c9b829bf7c5bb70c72f6c34

**Comment by robertej-phd** [comment]
I'm working on this now but this requires a major restructuring of the code base due to where we are handling parsing the scard, etc. Am working on this in my fork on branch "dbschema_v2"

**Comment by robertej-phd** [comment]
Closing this now after PR #23, see DB at time of this PR at https://dbdiagram.io/d/5c9b829bf7c5bb70c72f6c34

I'm sure there will be more changes to the DB in the near future, if they are minor they will be mentioned somewhere, if they are major make an issue, implement the changes, and make a PR
