### ISSUE TITLE
directories support

### ISSUE THREAD

**Issue by maureeungaro** [mit-mc-clas12/clas12simulations#20]
We'll need this for the gcards, the generator, the background merging. 

Basically the gcard entry (or the others) should support an entire directory containing gcards.
Then the simulation is duplicated with the exact same conditions except it will use each gcard in the directory.

When we discussed this I proposed a directory visible by the submit scripts (same machine). But it could get complicated. 

I propose one mechanism only, to read directories visible online. The python script could use wget to get them.

Example for the gcard:

gcard:  https://username.jlab.org/ungaro/tmp/gcards   

The script would download the entire directory and execute N condor submits, one for each gcard in there.

**Comment by Sangbaek** [comment]
The link doesn't work for me. Do you mean link like [https://userweb.jlab.org/~ungaro/tmp/](https://userweb.jlab.org/~ungaro/tmp/)? I cannot find the directory gcards there either though.

**Comment by robertej-phd** [comment]
Hi, just wanted to say that the link (https://username.jlab.org/ungaro/tmp/gcards) also does not work for me. 

Additionally, what is meant by "background merging"?

**Comment by robertej-phd** [comment]
Closing as gcard directory is now supported; making a separate issue to handle background merging requests, an issue already exists for handling user input files
