### ISSUE TITLE
Change keys of genOutput, genExecutable to match current documentation

### ISSUE THREAD

**Issue by Sangbaek** [mit-mc-clas12/clas12simulations#26]
From line 200~ of file_struct.py

Keys of genOutput and genExecutable were name of generators themselves at March collaboration meeting. I.e. dvcsgen and generate-dis were used instead of dvcs and dis-rad. Please respect consistency. Please check https://clasweb.jlab.org/clas12/clas12SoftwarePage/html/tutorials/subMit/p1.html

A possible improvement would be to query (either every time or periodically with a cronjob) an online repository, using urllib2 for example, and parse a file structure, instead of statically defining these dictionaries in file_struct.py

**Comment by robertej-phd** [comment]
Edited original issue, split into two different issues (see issue #32)

**Comment by robertej-phd** [comment]
Moved to mit-mc-clas12/server
