### ISSUE TITLE
Some version of templates missing at some point

### ISSUE THREAD

**Issue by Sangbaek** [mit-mc-clas12/clas12simulations#27]
Eventually templates will not be used so every script should be written from scratch from db but for some notes..

1.
Luminosity option used at March tutorial was
"
-LUMI_EVENT="NLUMI, 248.5*ns, 4*ns" -LUMI_P="e-, 10.6*GeV, 0*deg, 0*deg" -LUMI_V="(0.0, 0.0, -10)cm" -LUMI_SPREAD_V="(0.03, 0.03)cm”
"
The missing templates had an option to change NLUMI i luminosity was not 0 at scard.

2.
 gcards_scard is not correctly replaced at copying gcard, i.e.
cp gcards_scard out_`basename $ClusterId`_nnevents_scard
is changed to 
cp https://userweb.jlab.org/~ungaro/tmp/gcards/ out_`basename $ClusterId`_n10
by python codes for example.
The url should be replaced with directory path like $/src/utils/../../submission_files/gcards/gcard_8_batch_4.gcard.

**Comment by robertej-phd** [comment]
Moved to mit-mc-clas12/server
