### ISSUE TITLE
Create tests for pull requests / CI

### ISSUE THREAD

**Issue by robertej-phd** [mit-mc-clas12/clas12simulations#39]
It might be helpful to start setting up validation tests to aid with pull requests so we don't have to manually test a bunch of edge cases every time we have a PR. We could use something like https://travis-ci.org/. I haven't had to set this up myself on any previous projects, but should be mostly straightforward. Perhaps we can discuss this at our next group meeting.

**Comment by Sangbaek** [comment]
The permission to travis is now granted. We might want to add yaml file. Personally I am really bad at this, I tried bitbucket pipeline with their yaml file structure but I failed everytime. But it's worth trying. For more info:
https://docs.travis-ci.com/user/tutorial/

**Comment by Sangbaek** [comment]
I tried very simple .travis.yml:
```
language: python
python:
  - "2.6"
  - "2.7"
script:
  - coverage run src/Submit_Job.py -s scard.txt
```

But the build failed, no surprise (as I experienced at pipeline!). Here are some more complicated examples of travis:
https://docs.travis-ci.com/user/languages/python/#examples

**Comment by Sangbaek** [comment]
At least this works. I can add .travis.yml after next PR or please add .travis.yml with following contents.
```
language: python
python:
  - "2.7"
# command to run tests
script:
  - python src/Submit_Job.py
```
