### ISSUE TITLE
Grab submitted job ID number from HTCondor

### ISSUE THREAD

**Issue by robertej-phd** [mit-mc-clas12/clas12simulations#40]
When submitting a job using HTCondor, we get a message such as: 
```jobs 7482391...98 submitted successfully```

We will at the end of the day need these HTCondor job IDs for logging purposes, which can maybe be accomplished with something like ```subprocess.check_output()```

**Comment by Sangbaek** [comment]
According to http://chtc.cs.wisc.edu/condor_q.shtml
condor_q -nobatch will help this issue.

In c-shell,
set string = `condor_q -nobatch`
echo "$string"
will work.

**Comment by robertej-phd** [comment]
I believe this is handled now, PR forthcoming. Used essentially subprocess.check_output()
