### ISSUE TITLE
Build setup.py for sake of simplicity

### ISSUE THREAD

**Issue by Sangbaek** [mit-mc-clas12/clas12simulations#43]
Related to #39.

Currently, we're trying individual shell commands for python
e.g. ) python utils/*.py etc etc.

I'm suggesting to write a setup.py which captures libraries and main scripts at the same time, to make other users easily execute our codes.

**Comment by robertej-phd** [comment]
Does "Submit_Job.py" cover this functionality?

**Comment by Sangbaek** [comment]
Well, I think it's true, and I don't feel the necessity of installing the package anymore.
