### ISSUE TITLE
Enable Job Submission on Holyoke Computing Pool 

### ISSUE THREAD

**Issue by robertej-phd** [mit-mc-clas12/clas12simulations#5]
Through SubMIT or directly, we should be able to submit jobs to Holyoke. This should be done if possible.

**Comment by Sangbaek** [comment]
Now MIT students got access to Holyoke, a Slurm farm at MIT. I tried to get root permission, but it didn't work. How do we install cvmfs at the farm?

**Comment by robertej-phd** [comment]
Moved to mit-mc-clas12/server
