### ISSUE TITLE
One run script file, not 3

### ISSUE THREAD

**Issue by robertej-phd** [mit-mc-clas12/clas12simulations#6]
Currently on some computing pools (Tier 2, maybe other) we have 3 submission scripts: condor_wrapper, run_job, and runscript.sh. These should be combined intelligently to create 1 run script file. If we need to create separate templates to run on Tier 2 vs. OSG, maybe we should do this, and then call which template to overwrite based on which pool we are submitting to.

**Comment by Sangbaek** [comment]
The critical point of making 3 script is to run following line.

exec singularity exec --home $PWD --bind $PWD:/tmp --bind /cvmfs $SingularityImage $LOCALDIR/"$@"

Current structure is
run_job.sh -> condor_wrapper -> runscript.sh
We can easily reduce the scripts to 2 by skipping condor_wrapper.
 But I don't know how to import path without
"singularity exec" a separate script (runscript.sh for our case.)
I tried singularity shell but failed.

**Comment by Sangbaek** [comment]
We need to make 1 template works for both osg and subMIT after this issue is solved.

**Comment by robertej-phd** [comment]
Not very important, closing.
